routes/web.php
<?php

use App\Http\Controllers\Backend\ContactUsSubmission\ContactUsSubmissionController as BackendSubmissionsController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontent\ContactUsSubmission\ContactUsSubmissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('contact-us', [ ContactUsSubmissionController::class, 'create' ])->name('frontend.contact-us.create');

Route::post('contact-us', [ ContactUsSubmissionController::class, 'store' ])->name('frontend.contact-us.store');

Route::prefix('backend')->middleware('auth')->as('backend.')->group(function () {
    Route::get('/contact-us', [BackendSubmissionsController::class, 'index'])->name('contact-us.index');
    Route::get('/contact-us/{contact_us_submission}', [BackendSubmissionsController::class, 'show'])->name('contact-us.show');
});

app/Models/ContactUsSubmission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ContactUsSubmission extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/Traits/UserAttributesTrait.php
<?php

namespace App\Models\Traits;

trait UserAttributesTrait
{
    public function setPasswordAttribute($plainPassword)
    {
        $this->attributes['password'] = bcrypt($plainPassword);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use App\Models\Traits\UserAttributesTrait;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, UserAttributesTrait;

    const ADMIN_EMAIL = 'admin@test.com';

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/ContactUsSubmission/ContactUsSubmissionController.php
<?php

namespace App\Http\Controllers\Backend\ContactUsSubmission;

use App\Http\Controllers\Controller;
use App\Models\ContactUsSubmission;
use App\Repositories\Backend\ContactUsSubmissionRepository;
use Illuminate\Http\Request;

class ContactUsSubmissionController extends Controller
{
    protected $repository;

    public function __construct(ContactUsSubmissionRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $submissions = $this->repository->getPaginated(25, 'id', 'desc');

        return view('backend.contact_us.index', [
            'submissions' => $submissions
        ]);
    }

    public function show(ContactUsSubmission $contactUsSubmission)
    {
        return view('backend.contact_us.show', [
            'submission' => $contactUsSubmission
        ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Frontent/ContactUsSubmission/ContactUsSubmissionController.php
<?php

namespace App\Http\Controllers\Frontent\ContactUsSubmission;

use Illuminate\Http\Request;
use Illuminate\Contracts\View\View;
use App\Http\Controllers\Controller;
use App\Http\Requests\Frontend\ContactSubmissioStoreRequest;
use App\Repositories\Frontend\ContactUsSubmissionRepository;

class ContactUsSubmissionController extends Controller
{
    private $contactRepository;

    public function __construct(ContactUsSubmissionRepository $contactRepository)
    {
        $this->contactRepository = $contactRepository;
    }

    public function create(): View
    {
        return view('frontend.contact_us_submissions.create');
    }

    public function store(ContactSubmissioStoreRequest $request)
    {
        $this->contactRepository->store($request->all());

        return redirect()->route('frontend.contact-us.create')->withFlashSuccess('Thank you for contacting us, we will get back to you shortly!');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/View/Components/Alert.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Alert extends Component
{
    public $type;
    public $message;

    /**
     * Create a new component instance.
     *
     * @param string $type
     * @param string $message
     */
    public function __construct(string $type, string $message)
    {
        $this->type = $type;
        $this->message = $message;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.alert');
    }
}

resources/views/backend/contact_us/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Created At</th>
        <th scope="col">Ago</th>
        <th scope="col">Show</th>
        </tr>
    </thead>
    <tbody>
        @foreach($submissions as $submission)
        <tr>
            <th scope="row">{{ $submission->id }}</th>
            <td>{{ $submission->name }}</td>
            <td>{{ $submission->email }}</td>
            <td>{{ $submission->phone }}</td>
            <td>{{ $submission->created_at->format('Y-m-d H:i') }}</td>
            <td>{{ $submission->created_at->diffForHumans() }}</td>
            <td>
                <a href="{{ route('backend.contact-us.show', $submission->id) }}">
                    Show
                </a>
                
            </td>
        </tr>
        @endforeach
    </tbody>
    </table>

    <div class="d-flex justify-content-center">
        {{ $submissions->render() }}
    </div>

</div>
@endsection

resources/views/backend/contact_us/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row border-bottom mb-4 p-2">
            <div class="col-md-4">
                Name
            </div>

            <div class="col-md-8">
                {{ $submission->name }}
            </div>
        </div>

        <div class="row border-bottom mb-4 p-2">
            <div class="col-md-4">
                Email
            </div>

            <div class="col-md-8">
                {{ $submission->email }}
            </div>
        </div>

        <div class="row border-bottom mb-4 p-2">
            <div class="col-md-4">
                Phone
            </div>

            <div class="col-md-8">
                {{ $submission->phone }}
            </div>
        </div>

        <div class="row border-bottom mb-4 p-2">
            <div class="col-md-4">
                Address
            </div>

            <div class="col-md-8">
                {{ $submission->address }}
            </div>
        </div>

        <div class="row border-bottom mb-4 p-2">
            <div class="col-md-4">
                Message
            </div>

            <div class="col-md-8">
                {{ $submission->message }}
            </div>
        </div>

        <div>
            <a href="{{ route('backend.contact-us.index') }}" class="btn btn-primary"> Back </a>
        </div>

    </div>

@endsection

resources/views/flash_messages/index.blade.php
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        @if(session()->has('flash_success'))
            @php
                $message = session('flash_success');
            @endphp
            <x-alert type="success" :message="$message"></x-alert>
        @endif

        @if(session()->has('flash_error'))
            @php
                $message = session('flash_error');
            @endphp
            <x-alert type="danger" :message="$message"></x-alert>
        @endif

        @if ($errors->any())

        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @endif
        </div>
    </div>
</div>

resources/views/frontend/contact_us_submissions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Contact us</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('frontend.contact-us.store') }}" novalidate>
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">
                                Name
                                <span class="text-danger">*</span>
                            </label>

                            <div class="col-md-6">
                                <input id="name" type="name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">
                                Email-Address
                                <span class="text-danger">*</span>
                            </label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                    
                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">
                                Phone
                                <span class="text-danger">*</span>
                            </label>

                            <div class="col-md-6">
                                <input id="phone" type="phone" 
                                class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" 
                                required autocomplete="phone" 
                                autofocus>

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">
                                Address
                            </label>

                            <div class="col-md-6">
                                <textarea id="address"
                                    class="form-control"  
                                    name="address"
                                ></textarea>
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="message" class="col-md-4 col-form-label text-md-right">
                                Message
                                <span class="text-danger">*</span>
                            </label>

                            <div class="col-md-6">
                                <textarea id="message"
                                    class="form-control @error('message') is-invalid @enderror"  
                                    name="message"
                                ></textarea>

                                @error('message')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>

                                <a class="btn btn-danger" href="{{ route('home') }}">
                                    Cancel
                                </a>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <a href="{{ route('frontend.contact-us.create') }}">Contact Form</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Komodo Interview Test') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->

                        <li class="nav-item">
                                <a class="nav-link" href="{{ route('frontend.contact-us.create') }}">Contact Form</a>
                        </li>

                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                        @else

                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('backend.contact-us.index') }}">From Submissions</a>
                            </li>

                        
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>

                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            
            @include('flash_messages.index')
            
            @yield('content')
        </main>
    </div>
</body>
</html>